plonky2x/src/backend/circuit/utils.rs, plonky2x/src/frontend/eth/storage/builder.rs, plonky2x/src/frontend/eth/storage/generators/block.rs, plonky2x/src/frontend/eth/storage/generators/storage.rs, plonky2x/src/frontend/eth/storage/utils.rs, plonky2x/src/frontend/eth/storage/vars/block.rs, plonky2x/src/frontend/hash/keccak/keccak256.rs, plonky2x/src/frontend/hash/keccak/mod.rs, plonky2x/src/frontend/hash/mod.rs, plonky2x/src/utils/lido/mod.rs
- Implement generator for getStorageKeyAt
- Add `Keccak256Generator`
=> feat: getStorageKeyAt

plonky2x/src/backend/circuit/utils.rs, plonky2x/src/frontend/eth/storage/builder.rs, plonky2x/src/frontend/eth/storage/generators/block.rs, plonky2x/src/frontend/eth/storage/vars/block.rs
Update `Block` to include `u64` data type for `blockNumber`, add `gasUsed`, `gasLimit` and `time`
- Need to add support for variable bytes (ex. bloom, extra)
=> feat: update getBlockByHash

plonky2x/src/backend/circuit/utils.rs, plonky2x/src/frontend/eth/storage/builder.rs, plonky2x/src/frontend/eth/storage/generators/block.rs, plonky2x/src/frontend/eth/storage/generators/storage.rs, plonky2x/src/frontend/eth/storage/vars/block.rs, plonky2x/src/frontend/eth/storage/vars/storage.rs
- Add eth_getTransactionLog
- Update order of variables for eth_getStorageAt to reflect natural order `blockHash`, `address`, `storageKey`
- Update offsets to be more explicit
=> feat: eth_getTransactionLog

Cargo.lock, plonky2x/src/frontend/vars/array.rs
Enable accessing the element at an index of an `ArrayVariable`.
=> feat(plonky2x): ArrayVariable index accessor

plonky2x/src/frontend/builder/mod.rs, plonky2x/src/frontend/hash/sha/sha256_curta.rs, plonky2x/src/frontend/merkle/tendermint.rs
- Builder will now automatically invoke `curta_constrain_sha256` if a developer calls `curta_sha256` in a circuit.
=> feat(plonky2x): constrain curta_sha256 in builder

plonky2x/src/frontend/num/u32/gadgets/range_check.rs
- The `u32_range_check` gate needed to be separated into multiple rows to handle range checking more than 7 limbs at a time.
=> fix(plonky2x): chunk u32_range_check into multiple rows

Cargo.lock, plonky2x/src/frontend/vars/bytes.rs
- Support index and slice on `BytesVariable`. Helps replace legacy `extract_hash_from_protobuf` in zkQGB and will be useful in parity between `BytesVariable` and `ArrayVariable`.
=> feat(plonky2x): implement `range` and `index` on `BytesVariable`

Cargo.lock, plonky2x/src/backend/circuit/build.rs, plonky2x/src/backend/circuit/serialization/hints.rs, plonky2x/src/backend/circuit/witness.rs, plonky2x/src/frontend/hint/asynchronous/builder.rs, plonky2x/src/frontend/hint/asynchronous/channel.rs, plonky2x/src/frontend/hint/asynchronous/generator.rs, plonky2x/src/frontend/hint/asynchronous/hint.rs, plonky2x/src/frontend/hint/simple/hint.rs
Remove concurrency locks in async hint generation.
=> fix(Plonky2x): async hint

contracts/.env.example, contracts/README.md, contracts/script/deploy/FunctionGateway.s.sol, contracts/script/upgrade.sh
Add deploy and upgrade script instructions.
=> feat: contract upgrades

contracts/src/interfaces/IFunctionGateway.sol, contracts/test/FunctionGateway.t.sol, contracts/test/TestUtils.sol
Output:
```sh
Running 8 tests for test/FunctionGateway.t.sol:FunctionGatewayTest
[PASS] test_Call() (gas: 189243)
[PASS] test_Call_WhenNoFee() (gas: 189242)
[PASS] test_Callback() (gas: 167927)
[PASS] test_Callback_WhenNoFee() (gas: 167833)
[PASS] test_RevertCall() (gas: 124608)
[PASS] test_RevertCallback() (gas: 28990)
[PASS] test_RevertVerifiedCall() (gas: 23436)
[PASS] test_VerifiedCall() (gas: 23696)
Test result: ok. 8 passed; 0 failed; 0 skipped; finished in 4.62ms
```
=> test: coverage for FunctionGateway

contracts/README.md, contracts/script/deploy.sh, contracts/script/deploy/SuccinctGateway.s.sol, contracts/src/SuccinctGateway.sol, contracts/src/examples/StorageOracle.sol, contracts/src/interfaces/ISuccinctGateway.sol, contracts/src/mocks/MockSuccinctGateway.sol, contracts/test/SuccinctGateway.t.sol, contracts/test/TestUtils.sol, contracts/test/examples/NounsOwnership.t.sol
Renames `FunctionGateway` to `SuccinctGateway`
=> refactor: FunctionGateway -> SuccinctGateway

contracts/src/SuccinctGateway.sol, contracts/test/SuccinctGateway.t.sol, contracts/test/TestUtils.sol
If Gateway is deployed with address(0), everything still works.
=> feat: allow no for FeeVault in Gateway

contracts/src/FunctionRegistry.sol, contracts/src/interfaces/IFunctionRegistry.sol, contracts/src/interfaces/ISuccinctGateway.sol, contracts/test/SuccinctGateway.t.sol
Only relevant file changes are in `contracts/src/FunctionRegistry.sol`.
=> feat: specify owner for Function when registering

contracts/src/SuccinctGateway.sol, contracts/src/interfaces/ISuccinctGateway.sol, contracts/src/upgrades/Versioned.sol, contracts/test/SuccinctGateway.t.sol, contracts/test/TestUtils.sol
`fulfillCallback` and `fulfillCall` can only be called by a prover.
=> feat: onlyProver for Gateway

plonky2x/core/src/frontend/eth/rlp/builder.rs
Replace the generator with the hint in RLP decoding.
=> chore: replace generator with hint in RLP decoding

contracts/README.md, contracts/script/verify.sh
Necessary to use this if automatic verification fails.
=> fix: contract verify script

plonky2x/core/src/frontend/merkle/mod.rs, plonky2x/core/src/frontend/merkle/simple.rs, plonky2x/core/src/frontend/merkle/tendermint.rs
- Add simple merkle tree.
- Clean up existing Tendermint merkle tree.
=> feat: simple merkle tree

contracts/src/FunctionRegistry.sol, contracts/src/SuccinctGateway.sol, contracts/src/payments/SuccinctFeeVault.sol
Should override all functions declared in interfaces (IFunctionRegistry, ISuccinctGateway, IFeeVault).
Audit Issue: https://veridise.notion.site/Contracts-Code-Recommendations-8d66e85361424956a508b3c602ef8783 (1)
=> chore: specify contract function overrides

contracts/src/FunctionRegistry.sol, contracts/test/SuccinctGateway.t.sol
Code is similar, so there is an opportunity to reduce some code duplication. 
Note: some of the revert situations are less gas efficient than before, but that seems lower priority than more readable and maintainable code.
Audit Issue: https://veridise.notion.site/Contracts-Code-Recommendations-8d66e85361424956a508b3c602ef8783 (2)
=> refactor: FunctionRegistry shared functions

client/src/utils.rs, contracts/README.md
Add gateways for Arbitrum and Arbitrum-Sepolia.
=> feat(succinct-client): add gateways

client/src/request.rs, client/src/utils.rs, contracts/README.md
Also add debug message for when there is no canonical gateway deployment found.
=> fix: rm broken optimism gateway

plonky2x/core/src/backend/circuit/serialization/hints.rs, plonky2x/core/src/frontend/curta/proof.rs, plonky2x/core/src/frontend/ecc/curve25519/curta/builder.rs, plonky2x/core/src/frontend/eth/mpt/builder.rs, plonky2x/core/src/frontend/eth/mpt/generators.rs, plonky2x/core/src/frontend/eth/mpt/rlc.rs, plonky2x/core/src/frontend/eth/storage/builder.rs, plonky2x/core/src/frontend/hash/keccak/mod.rs, plonky2x/core/src/frontend/ops/math.rs, plonky2x/core/src/frontend/vars/stream.rs
…enerator/hint result (#246)"
This reverts commit 8ce56b8b09d6d444c2d81d9853fabeaa55a8e409.
=> fix: revert previous commit

contracts/src/libraries/OutputReader.sol, contracts/test/libraries/OutputReader.t.sol
Add documentation for `OutputReader` and additional tests for other `uint`'s. No code changes.
=> docs: output reader
