Cargo.toml, plonky2x/Cargo.toml
Import path for plonky2x-derive was broken when importing from external repo, change to relative path.
=> fix: import plonky2x-derive

plonky2x/src/backend/circuit/mod.rs
Currently, the `Circuit` trait definition has underscores under `gate_registry` and `generator_registry` because of unused variables warning of clippy. 
However, this is going to be a little misleading for users implementing the trait because the rust IDE autocomplete will also introduce these underscores. 
Instead, this PR just uses `#[allow(unused_variables)]`.
=> fix(Plonky2x): underscores in `Circuit` trait

plonky2x/src/frontend/merkle/tendermint.rs
- Add function to generate merkle proof given a hashed leaf. This is useful for situations where the leaf hash requires a variable `sha256` hash.
- Remove unnecessary function bounds for `AlgebraicHasher`
=> feat(plonky2x): extend merkle tree

Cargo.lock, plonky2x/Cargo.toml, plonky2x/src/frontend/hash/keccak/mod.rs, plonky2x/src/frontend/merkle/tendermint.rs
- Remove `NB_LEAVES_ENABLED` as const generic, for most circuits, `NB_LEAVES_ENABLED` will be variable and it's more idiomatic to pass in a `leaves_enabled` array.
- Refactor tests for `tendermint` to follow new `CircuitBuilder` format.
- Update `curta` branch to `main`
=> refactor(plonky2x): tendermint merkle tree

plonky2x/src/backend/circuit/serialization/hints.rs, plonky2x/src/frontend/curta/hash/sha/sha256/builder.rs, plonky2x/src/frontend/curta/hash/sha/sha256/hint.rs, plonky2x/src/frontend/curta/hash/sha/sha256/mod.rs, plonky2x/src/frontend/hash/sha/sha256_curta.rs, plonky2x/src/frontend/vars/stream.rs
- Add `async_hint` for `curta_sha256` to `succinctx`, enables `sha256` gadgets to be run async.
- ~2x speedup over sync `sha256` with 10 gadgets, takes advantage of unallocated cores.
=> feat(plonky2x): sha256 curta async hint

plonky2x/core/src/frontend/ops/math.rs
- Previously the comparisons in `gte` and `gt` was incorrect, this PR corrects them and adds corresponding tests.
=> fix: `gte` and `gt` cmp

plonky2x/core/src/frontend/ecc/ed25519/gadgets/curve.rs
- Mirror logic from `compress_point` to return a `Bytes32Variable` when compressing points.
=> feat: add `compress_point_variable`

Cargo.lock, plonky2x/core/src/frontend/vars/array.rs
- Use RLC trick to simplify `get_fixed_subarray`, and make usable for extracting subarrays from large header sizes.
=> fix: `get_fixed_subarray` using rlc

contracts/src/SuccinctGateway.sol, contracts/src/interfaces/ISuccinctGateway.sol, contracts/test/SuccinctGateway.t.sol
Guardian can now update FeeVault address, and this acts as a way to disable fees since it can now be set to `address(0)`.
=> feat: option to disable fees for Gateway

contracts/.gitignore, contracts/src/FunctionRegistry.sol, contracts/src/interfaces/IFunctionRegistry.sol, contracts/test/SuccinctGateway.t.sol, contracts/test/TestUtils.sol
Fixes 2 bugs:
* functionId should always be calculated using `owner` instead of `msg.sender`
* should not allow updating a function if the verifier is the same
Adds tests for FunctionRegistry.
=> fix: FunctionRegistry bugs + tests

contracts/src/payments/SuccinctFeeVault.sol, contracts/src/payments/interfaces/IFeeVault.sol, contracts/test/payments/SuccinctFeeVault.t.sol
Output:
```sh
Running 5 tests for test/payments/SuccinctFeeVault.t.sol:CollectNativeTest
[PASS] test_CollectNative() (gas: 98280)
[PASS] test_CollectNative_WhenNotFullAmount() (gas: 98523)
[PASS] test_CollectNative_WhenZeroAmount() (gas: 66557)
[PASS] test_RevertCollectNative_WhenNotEnoughBalance() (gas: 21160)
[PASS] test_RevertCollectNative_WhenNotOwner() (gas: 21030)
Test result: ok. 5 passed; 0 failed; 0 skipped; finished in 4.50ms
Running 6 tests for test/payments/SuccinctFeeVault.t.sol:DeductNativeTest
[PASS] test_DeductNative() (gas: 46735)
[PASS] test_DeductNative_WhenNotDeductor() (gas: 56006)
[PASS] test_DeductNative_WhenNotFullAmount() (gas: 63804)
[PASS] test_DeductNative_WhenSameAccount() (gas: 45149)
[PASS] test_DeductNative_WhenSameAccountMultipleSpenders() (gas: 59139) …
```
=> test: coverage for SuccinctFeeVault

plonky2x/core/src/frontend/curta/ec/point.rs, plonky2x/core/src/frontend/hash/sha/sha512/pad.rs
Extend the input to `pad_sha512` to size `max_num_chunks` * 128.
=> fix(plonky2x): `sha512_pad`

plonky2x/core/src/frontend/merkle/mod.rs, plonky2x/core/src/frontend/merkle/tendermint.rs, plonky2x/core/src/frontend/merkle/utils.rs, plonky2x/core/src/utils/lido/mod.rs
Previously, `get_root_from_hashed_leaves` required an input that had a length that was a power of 2. Now, it pads to the nearest power of 2 greater than the input length.
=> refactor(plonky2x): `get_root_from_hashed_leaves`

plonky2x/core/src/backend/circuit/serialization/hints.rs
Register missing hints for `EcOp` and `SHA512` to serialize circuits.
=> fix(plonky2x): register EcOp and SHA512 hints

plonky2x/core/src/frontend/ecc/curve25519/ed25519/eddsa.rs, plonky2x/core/src/frontend/hash/sha/sha512/curta.rs, plonky2x/core/src/frontend/hash/sha/sha512/pad.rs
- `curta_eddsa_verify_sigs_conditional`
- Add test for `sha512_pad`. Previously, the `max_num_chunks` was calculated incorrectly.
=> fix: eddsa + sha512 pad fixes

plonky2x/core/src/backend/circuit/build.rs, plonky2x/core/src/backend/wrapper/wrap.rs
- Use `curta_sha256` in `plonky2x` wrapper to handle large public inputs better.
- On Mac M2 Max for wrapping now takes ~4s, vs. ~2s before.
- Add `prove_with_partial_witness` and `prove_with_partial_witness_async` to `Plonky2x` circuits, allowing plonky2 `PartialWitness` to be used to generate proofs directly, without using `plonky2x` IO.
=> feat(plonky2x): use `curta_sha256` in wrapper

plonky2x/core/src/frontend/uint/num/u32/gates/add_many_u32.rs
The `U32AddManyGate` has a constant that specifies the max number of inputted operands that is original set to 16 (compliance is only debug_asserted).  (log base 2 of that constant)/2 determines how many 4-bit limbs to store the carry (2 this case).
When multiplying two 512 bit numbers, the number of operands into the U32AddManyGate can be as large as 31.  This resulted in a carry that could overflow carry limbs.
To fix this, the max number of inputted operands constant and it's log constant is increased.
=> fix: uint512 mul bug fix

contracts/src/FunctionRegistry.sol, contracts/src/SuccinctGateway.sol, contracts/src/interfaces/ISuccinctGateway.sol, contracts/test/SuccinctGateway.t.sol
Function owners can now specify if they want to use the default prover, a custom prover that they specify, or disable whitelisted proving altogether.
Audit Issue: https://veridise.notion.site/Contracts-Centralization-Risk-ec97d40516f3487eb907f2bd01f6135c Different from the recommended solution, but this solution was also with keeping in mind with some feedback from users.
=> feat: custom prover whitelist 

contracts/src/SuccinctGateway.sol, contracts/test/SuccinctGateway.t.sol, contracts/test/TestUtils.sol
Although we generally will always need to simulate before sending for `fullfill*()` transactions, this makes sense to add given the requester specifies it.
Audit Issue: https://veridise.notion.site/Contracts-_callbackGasLimit-is-unused-86702937b6964a40a049b9e310ed3a8a Note since we simulate the transaction first, there is less of a need to use `ExcessivelySafeCall`.
=> fix: use callbackGasLimit to callback contract

contracts/src/SuccinctGateway.sol, contracts/src/interfaces/ISuccinctGateway.sol, contracts/test/SuccinctGateway.t.sol
Because the `request*()` functions accept fees even when the feeVault is not set:
```solidity
if (feeVault != address(0)) {
IFeeVault(feeVault).depositNative{value: msg.value}(callbackAddress);
}
```
it is possible for the contract to have some stuck funds in the SuccinctGateway. This change allows the guardian to recover the funds.
Audit Issue: https://veridise.notion.site/Contracts-funds-may-be-locked-when-feeVault-is-disabled-5c75f079cead42d696143c4bf234bcfc
---
Also adds:
delete instead of setting to zero reduces gas costs for removeProver.
Audit Issue: https://veridise.notion.site/Contracts-Possible-Wasted-Gas-3860531b4bc4471d91fe21117a8a281a (other suggestions are being addressed in other PRs)
=> feat: recover funds from SuccinctGateway

Cargo.lock, client/Cargo.toml, client/abi/SuccinctGateway.abi.json, client/src/lib.rs, client/src/request.rs, client/src/utils.rs
Add local relaying of proofs to the `SuccinctClient`. For now, local relaying is only supported if local proving is enabled.
=> feat(succinct-client): local relaying

contracts/.env.example, contracts/README.md, contracts/script/deploy/SuccinctFeeVault.s.sol, contracts/script/deploy/SuccinctGateway.s.sol, contracts/src/SuccinctGateway.sol, contracts/src/payments/SuccinctFeeVault.sol, contracts/test/SuccinctGateway.t.sol, contracts/test/payments/SuccinctFeeVault.t.sol
Removes timelocked upgradeability from SuccinctGateway and SuccinctFeeVault.
=> feat: non-upgradeable contracts

contracts/foundry.toml
Saves several thousand gas on the fulfill functions. Tested higher runs but no improvement after 100_000.
=> chore: update foundry.toml with optimizer

plonky2x/core/src/backend/wrapper/mod.rs, plonky2x/core/src/backend/wrapper/plonky2_config.rs, plonky2x/core/src/backend/wrapper/poseidon_bn128.rs
I've been using the PoseidonBN128 hash with plonky2 to do some benchmarking [here](https://github.com/shuklaayush/halo2-plonky2-verifier). Would be great if I could directly use the constants from the repo instead of redefining them
=> chore: make `poseidon_bn128` constants public

plonky2x/core/src/frontend/hash/sha/sha256/curta.rs, plonky2x/core/src/frontend/hash/sha/sha256/mod.rs, plonky2x/core/src/frontend/hash/sha/sha256/pad.rs, plonky2x/core/src/frontend/hash/sha/sha512/curta.rs, plonky2x/core/src/frontend/hash/sha/sha512/pad.rs
Assert the supplied variable `length` for `variable_sha256` & `variable_sha512` is less than the length of the supplied array.
=> fix(audit): refactor `pad_variable_length` for `sha256` + `sha512`

plonky2x/core/src/frontend/hash/blake2/curta.rs
Assert the `input_byte_length` is <= the length of the supplied input `ByteVariable` array.
Also, sets the correct column constants for `Blake2B` that were causing tests to fail on https://github.com/succinctlabs/succinctx/pull/331.
=> fix(audit): constrain blake2b variable input length

plonky2x/core/src/frontend/hash/sha/sha256/curta.rs
Remove unnecessary check on the size of input to `sha256_variable`. Extend inputs that to a multiple of 64 bytes if they are not already.
=> refactor(audit): sha256 variable

plonky2x/core/src/frontend/vars/array.rs
Previously, `get_fixed_subarray` was unsafe. 
Now, `get_fixed_subarray` computes the `subarray` from the `start_idx`, constructs the seed by appending the `subarray` to the existing `seed`. Then `extract_subarray` constrains the `subarray` correctly by verifying the accumulator is correct.
=> refactor: `get_fixed_subarray`

Cargo.lock, plonky2x/core/Cargo.toml, plonky2x/core/src/frontend/hash/blake2/curta.rs, plonky2x/core/src/frontend/hash/sha/sha256/curta.rs, plonky2x/core/src/frontend/hash/sha/sha512/curta.rs
This PR address two issues with blake2b related hash functions:
1) Fixed the case when the message is chunk aligned and not empty.  Basically, when the circuit was calculating the number of chunks of a message (or relatedly the idx of the last chunk), it was doing msg_len / chunk_len.  But if the msg_len is non zero and a multiple of chunk_len, that quotient value should be decremented by one.
2) In the pad_circuit_variable_length function (which is used when handling a blake2b request with variable size, it needed to replace all bytes after the inputted message len with zeros
=> fix: handle chunk aligned messages for blake2b

plonky2x/core/src/backend/circuit/serialization/hints.rs
The Watch generator here is pretty useful for integrations, this just allows others to use it.
Since the module presumes the crate name in the macro we just need a use alias so that the crate and downstream dependencies can use it as it.
=> chore: export watch generator

plonky2x/core/src/backend/prover/remote.rs
- Reduce the default timeout for proofs & batch proofs.
- Let users set configuration for proof and batch proof timeout via `PROOF_BATCH_TIMEOUT_SECS` and `PROOF_TIMEOUT_SECS`.
=> refactor: proof timeout
